// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/crawler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品状态枚举
type ItemStatus int32

const (
	ItemStatus_ITEM_STATUS_ON_SALE ItemStatus = 0 // 在售
	ItemStatus_ITEM_STATUS_SOLD    ItemStatus = 1 // 已售 (通过 thumbnail-sticker 判断)
)

// Enum value maps for ItemStatus.
var (
	ItemStatus_name = map[int32]string{
		0: "ITEM_STATUS_ON_SALE",
		1: "ITEM_STATUS_SOLD",
	}
	ItemStatus_value = map[string]int32{
		"ITEM_STATUS_ON_SALE": 0,
		"ITEM_STATUS_SOLD":    1,
	}
)

func (x ItemStatus) Enum() *ItemStatus {
	p := new(ItemStatus)
	*p = x
	return p
}

func (x ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crawler_proto_enumTypes[0].Descriptor()
}

func (ItemStatus) Type() protoreflect.EnumType {
	return &file_proto_crawler_proto_enumTypes[0]
}

func (x ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemStatus.Descriptor instead.
func (ItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{0}
}

// 爬虫请求
// 每个 IP 生成一个请求，分别抓取在售和已售商品
type CrawlRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	IpId    uint64                 `protobuf:"varint,1,opt,name=ip_id,json=ipId,proto3" json:"ip_id,omitempty"` // IP 数据库 ID (关联 ip_metadata.id)
	Keyword string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`        // 搜索关键词
	// 字段 3 保留 (历史原因)
	TaskId    string `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`           // 任务追踪 ID (UUID)
	CreatedAt int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 任务创建时间 (Unix 时间戳秒)
	// 重试相关
	RetryCount int32 `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"` // 已重试次数 (Janitor rescue 时递增)
	// 固定页数模式 (分别抓取在售和已售)
	PagesOnSale   int32 `protobuf:"varint,10,opt,name=pages_on_sale,json=pagesOnSale,proto3" json:"pages_on_sale,omitempty"` // 在售页数 (默认 5)
	PagesSold     int32 `protobuf:"varint,11,opt,name=pages_sold,json=pagesSold,proto3" json:"pages_sold,omitempty"`         // 已售页数 (默认 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlRequest) Reset() {
	*x = CrawlRequest{}
	mi := &file_proto_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlRequest) ProtoMessage() {}

func (x *CrawlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlRequest.ProtoReflect.Descriptor instead.
func (*CrawlRequest) Descriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlRequest) GetIpId() uint64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

func (x *CrawlRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CrawlRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CrawlRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CrawlRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *CrawlRequest) GetPagesOnSale() int32 {
	if x != nil {
		return x.PagesOnSale
	}
	return 0
}

func (x *CrawlRequest) GetPagesSold() int32 {
	if x != nil {
		return x.PagesSold
	}
	return 0
}

// 商品信息
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`      // 商品源 ID (如 m123456789 或 shops_xxx)
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                            // 商品标题
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                           // 价格 (日元)
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`      // 商品图片 URL
	ItemUrl       string                 `protobuf:"bytes,5,opt,name=item_url,json=itemUrl,proto3" json:"item_url,omitempty"`         // 商品详情页 URL
	Status        ItemStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=crawler.ItemStatus" json:"status,omitempty"` // 商品状态 (通过 HTML thumbnail-sticker 判断)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetItemUrl() string {
	if x != nil {
		return x.ItemUrl
	}
	return ""
}

func (x *Item) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ITEM_STATUS_ON_SALE
}

// 爬虫响应
type CrawlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	IpId  uint64                 `protobuf:"varint,1,opt,name=ip_id,json=ipId,proto3" json:"ip_id,omitempty"` // IP 数据库 ID
	// 字段 2 保留 (历史原因)
	Items        []*Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`                                     // 抓取到的商品列表 (从新到旧，在售+已售混合)
	TotalFound   int32   `protobuf:"varint,4,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`        // 页面上显示的总数 (如有)
	ErrorMessage string  `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`   // 错误消息 (成功时为空)
	TaskId       string  `protobuf:"bytes,6,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                     // 任务追踪 ID
	CrawledAt    int64   `protobuf:"varint,7,opt,name=crawled_at,json=crawledAt,proto3" json:"crawled_at,omitempty"`           // 抓取完成时间 (Unix 时间戳秒)
	PagesCrawled int32   `protobuf:"varint,10,opt,name=pages_crawled,json=pagesCrawled,proto3" json:"pages_crawled,omitempty"` // 实际翻页数
	// 重试相关
	RetryCount    int32 `protobuf:"varint,11,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"` // 已重试次数 (继承自 CrawlRequest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlResponse) Reset() {
	*x = CrawlResponse{}
	mi := &file_proto_crawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlResponse) ProtoMessage() {}

func (x *CrawlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlResponse.ProtoReflect.Descriptor instead.
func (*CrawlResponse) Descriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{2}
}

func (x *CrawlResponse) GetIpId() uint64 {
	if x != nil {
		return x.IpId
	}
	return 0
}

func (x *CrawlResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CrawlResponse) GetTotalFound() int32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

func (x *CrawlResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CrawlResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CrawlResponse) GetCrawledAt() int64 {
	if x != nil {
		return x.CrawledAt
	}
	return 0
}

func (x *CrawlResponse) GetPagesCrawled() int32 {
	if x != nil {
		return x.PagesCrawled
	}
	return 0
}

func (x *CrawlResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_proto_crawler_proto protoreflect.FileDescriptor

const file_proto_crawler_proto_rawDesc = "" +
	"\n" +
	"\x13proto/crawler.proto\x12\acrawler\"\x95\x02\n" +
	"\fCrawlRequest\x12\x13\n" +
	"\x05ip_id\x18\x01 \x01(\x04R\x04ipId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\"\n" +
	"\rpages_on_sale\x18\n" +
	" \x01(\x05R\vpagesOnSale\x12\x1d\n" +
	"\n" +
	"pages_sold\x18\v \x01(\x05R\tpagesSoldJ\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tR\x0eis_first_crawlR\ranchor_windowR\tmax_pages\"\xb4\x01\n" +
	"\x04Item\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x19\n" +
	"\bitem_url\x18\x05 \x01(\tR\aitemUrl\x12+\n" +
	"\x06status\x18\x06 \x01(\x0e2\x13.crawler.ItemStatusR\x06status\"\xbc\x02\n" +
	"\rCrawlResponse\x12\x13\n" +
	"\x05ip_id\x18\x01 \x01(\x04R\x04ipId\x12#\n" +
	"\x05items\x18\x03 \x03(\v2\r.crawler.ItemR\x05items\x12\x1f\n" +
	"\vtotal_found\x18\x04 \x01(\x05R\n" +
	"totalFound\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\atask_id\x18\x06 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"crawled_at\x18\a \x01(\x03R\tcrawledAt\x12#\n" +
	"\rpages_crawled\x18\n" +
	" \x01(\x05R\fpagesCrawled\x12\x1f\n" +
	"\vretry_count\x18\v \x01(\x05R\n" +
	"retryCountJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x0eis_first_crawlR\x11stopped_at_anchor*;\n" +
	"\n" +
	"ItemStatus\x12\x17\n" +
	"\x13ITEM_STATUS_ON_SALE\x10\x00\x12\x14\n" +
	"\x10ITEM_STATUS_SOLD\x10\x01B\x13Z\x11animetop/proto/pbb\x06proto3"

var (
	file_proto_crawler_proto_rawDescOnce sync.Once
	file_proto_crawler_proto_rawDescData []byte
)

func file_proto_crawler_proto_rawDescGZIP() []byte {
	file_proto_crawler_proto_rawDescOnce.Do(func() {
		file_proto_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crawler_proto_rawDesc), len(file_proto_crawler_proto_rawDesc)))
	})
	return file_proto_crawler_proto_rawDescData
}

var file_proto_crawler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_crawler_proto_goTypes = []any{
	(ItemStatus)(0),       // 0: crawler.ItemStatus
	(*CrawlRequest)(nil),  // 1: crawler.CrawlRequest
	(*Item)(nil),          // 2: crawler.Item
	(*CrawlResponse)(nil), // 3: crawler.CrawlResponse
}
var file_proto_crawler_proto_depIdxs = []int32{
	0, // 0: crawler.Item.status:type_name -> crawler.ItemStatus
	2, // 1: crawler.CrawlResponse.items:type_name -> crawler.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_crawler_proto_init() }
func file_proto_crawler_proto_init() {
	if File_proto_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crawler_proto_rawDesc), len(file_proto_crawler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_crawler_proto_goTypes,
		DependencyIndexes: file_proto_crawler_proto_depIdxs,
		EnumInfos:         file_proto_crawler_proto_enumTypes,
		MessageInfos:      file_proto_crawler_proto_msgTypes,
	}.Build()
	File_proto_crawler_proto = out.File
	file_proto_crawler_proto_goTypes = nil
	file_proto_crawler_proto_depIdxs = nil
}
